# Generated by Django 3.1.3 on 2020-12-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Report an issue', 'Report an issue'), ('Feature Request', 'Feature Request'), ('Improvement', 'Improvement'), ('General Comments', 'General Comments')], max_length=100, verbose_name='Feedback Category')),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
    ]
