# Generated by Django 3.1.3 on 2020-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201125_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='local_church',
            field=models.CharField(help_text='The name of your assembly without "A/G" as suffix', max_length=200),
        ),
    ]
